DROP TABLE meta;
DROP TABLE colaborador;
DROP TABLE cafeteria;
DROP TABLE piso;
DROP TABLE edificio;

CREATE TABLE edificio (
  id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre      VARCHAR2(255),

  PRIMARY KEY (id)
);

CREATE TABLE piso (
  id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  numeropiso  NUMBER,
  idEdificio  NUMBER,

  PRIMARY KEY (id),
  FOREIGN KEY (idEdificio) REFERENCES edificio (id)
    ON DELETE SET NULL
);

CREATE TABLE cafeteria (
  id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre      VARCHAR2(255),
  idPiso      NUMBER,

  PRIMARY KEY (id),
  FOREIGN KEY (idPiso) REFERENCES piso (id)
    ON DELETE SET NULL
);

CREATE TABLE colaborador (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre          VARCHAR2(255),
  tipodocumento   VARCHAR2(255),
  numerodocumento NUMBER,
  vinculacion     VARCHAR2(255) 
    CHECK (vinculacion IN ('PLANTA', 'TEMPORAL')),
  comision        NUMBER DEFAULT 10
    CHECK (comision >= 0 AND comision <= 100),

  PRIMARY KEY (id)
);

CREATE TABLE meta (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  fechameta     NUMBER,
  valormeta     NUMBER DEFAULT 0,
  valorreal     NUMBER DEFAULT 0,
  idCafeteria   NUMBER,
  idColaborador NUMBER,

  PRIMARY KEY (id),
  FOREIGN KEY (idCafeteria) REFERENCES cafeteria (id)
    ON DELETE SET NULL,
  FOREIGN KEY (idColaborador) REFERENCES colaborador (id)
    ON DELETE SET NULL
);
