CREATE TABLE edificio (
  id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre      VARCHAR2(255) NOT NULL,

  PRIMARY KEY (id)
);

CREATE TABLE piso (
  id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  numeropiso  NUMBER NOT NULL,
  idEdificio  NUMBER NOT NULL,

  PRIMARY KEY (id),
  FOREIGN KEY (idEdificio) REFERENCES edificio (id)
    ON DELETE SET NULL
);

CREATE TABLE cafeteria (
  id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre      VARCHAR2(255) NOT NULL,
  idPiso      NUMBER NOT NULL,

  PRIMARY KEY (id),
  FOREIGN KEY (idPiso) REFERENCES piso (id)
    ON DELETE SET NULL
);

CREATE TABLE colaborador (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre          VARCHAR2(255) NOT NULL,
  tipodocumento   VARCHAR2(255) NOT NULL,
  numerodocumento NUMBER NOT NULL,
  vinculacion     VARCHAR2(255) NOT NULL 
    CHECK (vinculacion IN ('PLANTA', 'TEMPORAL')),
  comision        NUMBER DEFAULT 10 NOT NULL
    CHECK (comision >= 0 AND comision <= 100),

  PRIMARY KEY (id)
);

CREATE TABLE meta (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  fechameta     NUMBER NOT NULL,
  valormeta     NUMBER DEFAULT 0 NOT NULL,
  valorreal     NUMBER DEFAULT 0 NOT NULL,
  idCafeteria   NUMBER NOT NULL,
  idColaborador NUMBER NOT NULL,

  PRIMARY KEY (id),
  FOREIGN KEY (idCafeteria) REFERENCES cafeteria (id)
    ON DELETE SET NULL,
  FOREIGN KEY (idColaborador) REFERENCES colaborador (id)
    ON DELETE SET NULL
);
